version: '2'
services:
    gcm-app:
        image: gcm
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gcm-postgresql:5432/GCM
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gcm-postgresql:
        extends:
            file: postgresql.yml
            service: gcm-postgresql
